//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Cargobay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Cargobay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to {0}.
        /// </summary>
        internal static string AccessTo {
            get {
                return ResourceManager.GetString("AccessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create file stream.
        /// </summary>
        internal static string CouldNotCreateFileStream {
            get {
                return ResourceManager.GetString("CouldNotCreateFileStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create FTP stream.
        /// </summary>
        internal static string CouldNotCreateFtpStream {
            get {
                return ResourceManager.GetString("CouldNotCreateFtpStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0}.
        /// </summary>
        internal static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}.
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: the transfer did not create a destination file.
        /// </summary>
        internal static string DestinationFileMissing {
            get {
                return ResourceManager.GetString("DestinationFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: the destination file still exists.
        /// </summary>
        internal static string DestinationFileStillExists {
            get {
                return ResourceManager.GetString("DestinationFileStillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string ExecuteCommandName {
            get {
                return ResourceManager.GetString("ExecuteCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed.
        /// </summary>
        internal static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been deleted.
        /// </summary>
        internal static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: the file still exists.
        /// </summary>
        internal static string FileStillExists {
            get {
                return ResourceManager.GetString("FileStillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} does not end with a backslash.
        /// </summary>
        internal static string FolderDoesNotEndWithBackslash {
            get {
                return ResourceManager.GetString("FolderDoesNotEndWithBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} does not exist.
        /// </summary>
        internal static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} ends with two backslashes.
        /// </summary>
        internal static string FolderEndsWithTwoBackslashes {
            get {
                return ResourceManager.GetString("FolderEndsWithTwoBackslashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} is located outside the sample area.
        /// </summary>
        internal static string FolderOutsideSampleArea {
            get {
                return ResourceManager.GetString("FolderOutsideSampleArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI is invalid.
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials for {0} are missing or invalid.
        /// </summary>
        internal static string NoAccessTo {
            get {
                return ResourceManager.GetString("NoAccessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: no connection could be made.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job has been selected.
        /// </summary>
        internal static string NoJobSelected {
            get {
                return ResourceManager.GetString("NoJobSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewCommandName {
            get {
                return ResourceManager.GetString("PreviewCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshJobs.
        /// </summary>
        internal static string RefreshJobsCommandName {
            get {
                return ResourceManager.GetString("RefreshJobsCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Machine).
        /// </summary>
        internal static string SecondaryMachine {
            get {
                return ResourceManager.GetString("SecondaryMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring changed file  {0}.
        /// </summary>
        internal static string TransferingChangedFile {
            get {
                return ResourceManager.GetString("TransferingChangedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring new file {0}.
        /// </summary>
        internal static string TransferingNewFile {
            get {
                return ResourceManager.GetString("TransferingNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred during upload, please transfer manually.
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading new file {0}.
        /// </summary>
        internal static string UploadingNewFile {
            get {
                return ResourceManager.GetString("UploadingNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the newest five files are being considered for upload.
        /// </summary>
        internal static string UploadReducedToNewestFiveFiles {
            get {
                return ResourceManager.GetString("UploadReducedToNewestFiveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded successfully.
        /// </summary>
        internal static string UploadSuccessful {
            get {
                return ResourceManager.GetString("UploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must start with &quot;{0}&quot;.
        /// </summary>
        internal static string UrlMustStartWith {
            get {
                return ResourceManager.GetString("UrlMustStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard.
        /// </summary>
        internal static string Wildcard {
            get {
                return ResourceManager.GetString("Wildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: a zip file has not been created.
        /// </summary>
        internal static string ZipFileMissing {
            get {
                return ResourceManager.GetString("ZipFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipping {0}.
        /// </summary>
        internal static string Zipping {
            get {
                return ResourceManager.GetString("Zipping", resourceCulture);
            }
        }
    }
}
